config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  post '/create/sub_comment', to: 'sub_comments#create', as: 'create_sub_comment'
  # get '/comment/:id/edit' , to: 'comments#edit' , as: 'comment_edit'
  patch '/posts/:post_id/comments/:comment_id/edit', to: 'comments#update', as: 'update_comment'
  get 'edit/sub_comment/:sub_comment_id', to: 'sub_comments#edit', as: 'edit_sub_comment'
  patch '/edit/sub_comment/:sub_comment_id', to: 'sub_comments#update', as: 'update_sub_comment'
  delete '/delete/sub_comment/:id', to: 'sub_comments#destroy', as: 'destroy_sub_comment'

  root 'posts#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signout', to: 'sessions#destroy', via: :delete

  post 'users/new', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_many :sub_comments
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  has_many :sub_comments
  belongs_to :user, required: true
  validates :user_id, presence: true
end

app/models/sub_comment.rb
class SubComment < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :post_comments

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      respond_to do |format|
        format.html {}
        format.js { render partial: 'comment' }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:comment_id])
    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to @post }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @comment.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'Comment deleted.'
        redirect_to @post
      end
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:create, :destroy, :edit]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
    @users = User.all
  end

  def show
    @new_comment = Comment.new
    @new_sub_comment = SubComment.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Post created.'
      redirect_to @post
    else
      render 'posts/new'
    end
  end

  def edit; end

  def update
    if @post.update_attributes(post_params)
      flash[:success] = 'The post was updated.'
      redirect_to @post
    else
      render 'posts/edit'
    end
  end

  def destroy
    if @post.destroy
      flash[:success] = 'Post deleted.'
      redirect_to root_path
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email].downcase)
    if @user && @user.authenticate(session_params[:password])
      sign_in @user
      redirect_back_or @user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/sub_comments_controller.rb
class SubCommentsController < ApplicationController
  def create
    @new_sub_comment = SubComment.new(sub_comment_params)
    @new_sub_comment.user = current_user

    respond_to?(&:js) if @new_sub_comment.save
  end

  def edit
    @sub_comment = SubComment.find(params[:sub_comment_id])
  end

  def update
    @post = Post.find(params[:post_id])
    @sub_comment = SubComment.find(params[:sub_comment_id])
    respond_to do |format|
      if @sub_comment.update_attributes(sub_comment_params)
        format.html { redirect_to @post }
      end
    end
  end

  def destroy
    @sub_comment = SubComment.find(params[:sub_comment_id])
    @post = Post.find(params[:post_id])
    @sub_comment.destroy
    respond_to do |format|
      format.html { redirect_to @post }
      format.json { head :no_content }
      format.js { render layout: false }
    end
  end

  private

  def sub_comment_params
    params.require(:sub_comment).permit(:body, :comment_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      redirect_to users_new_path, flash[:notice] = @user.errors.messages
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token # create a new token
    cookies.permanent[:remember_token] = remember_token # place the unencrypted token in the browser cookies ,
    # using permanent causes Rails to set the expiration to 20.years.from_now automatically.
    user.update_attribute(:remember_token, User.encrypt(remember_token)) # save the encrypted token to the database
    self.current_user = user # set the current user equal to the given user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: 'Please sign in.'
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/sub_comments_helper.rb
module SubCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if comment.present? %>
    <div id="comment_<%= comment.id %>" class="row single-comment vertical-align">
      <div class="comment clearfix">
        <div class="comment_content">

          <p><%= image_tag comment.user.avatar.url , size: '50x50' %></p>
          <p> Author: <%= comment.user.name%></p>
          <p class="date">
            <%= comment.body %>
            <% if current_user?(comment.user)%>
                | <%= link_to 'x',[comment.post, comment], method: :delete, data: { confirm: 'Delete comment?' },
                              id: "#{comment.id}_delete", remote: true,
                              title: 'Delete comment', rel: 'tooltip' %> |
                <%= link_to 'edit' , edit_post_comment_path(comment.post , comment)%>
            <% end %>
          </p>

        </div>
        <div id="comments_list">
          <%= render comment.sub_comments %>
        </div>
        <%= render 'sub_comments/sub_form' , comment: comment  %>
        <hr>

      </div>
    </div>
<% end %>

app/views/comments/_edit_form.html.erb
<%= form_for  @comment, url: update_comment_path(comment_id: @comment.id, post_id: @comment.post_id)  do |f| %>

    <div>
      <%= f.text_field :body %>
    </div>
    <div>
      <%= f.submit 'Update' %>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>What do <span class="you">you</span> think?</h3>

<%= form_for [@post, @new_comment], remote: true do |f| %>

    <%= render 'shared/error_messages', object: f.object %>


    <div class="form-group">
      <%= f.text_area :body, rows: '10', class: 'form-control' %>
    </div>

    <%= f.submit 'Post your comment', class: 'btn btn-default comment_submit' %>

<% end %>

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').remove();
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');

app/views/comments/edit.html.erb
<div id="edit_form">
    <%= render 'edit_form' %>
</div>

app/views/layouts/_headers.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "test blog", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
              <li><%= link_to "Add post" , new_post_path %></li>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Sign in", new_session_path %>
                    <%= link_to "Sign out", signout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogTest</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
<div class="container">
  <%= render 'layouts/headers' %>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <div class="post_wrapper">
      <h1 class="title"><%= link_to post.title, post %></h1>
      <p><%= image_tag post.user.avatar.url , size: '50x50' %></p>
       <p> user: <%= post.user.name %></p>
      <p class="date">created: <%= post.created_at.strftime("%B %d, %Y") %></p>
      <hr>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title"><%= @post.title %></h1>
  <p><%= image_tag @post.user.avatar.url , size: '100x100'%></p>
  <p>Author: <%= @post.user.name %></p>
  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> Ago
    <% if current_user?(@post.user) %>
        | <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <p class="body"><%= @post.body %></p>
  <hr>

  <div id="comments_list">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>
  </div>

  <div class="comment_form">
      <h3>Add a comment:</h3>
      <%= render "comments/form" %>
  </div>

</div>

app/views/static_pages/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", new_user_path, class: "btn btn-large btn-primary" %>
</div>

app/views/sub_comments/_edit_sub_comment.html.erb
<% byebug %>
<%= form_for  @sub_comment, url: update_sub_comment_path(post_id: @sub_comment.comment.post)  do |f| %>

    <div>
      <%= f.text_field :body %>
    </div>
    <div>
      <%= f.submit 'Update' %>
    </div>
<% end %>

app/views/sub_comments/_sub_comment.html.erb
<div id="sub_comment_<%= sub_comment.id %>" class="row single-comment vertical-align">

  <div class="sub_comment clearfix">
    <div class="sub_comment_content">

      <p><%= image_tag sub_comment.user.avatar.url , size: '50x50' %></p>
      <p> Author: <%= sub_comment.user.name%></p>
      <p class="date">
        <%= sub_comment.body %>
        <% if current_user?(sub_comment.user)%>
            | <%= link_to 'x',destroy_sub_comment_path(sub_comment_id: sub_comment.id, post_id: sub_comment.comment.post),
                         method: :delete, data: { confirm: 'Delete comment?' },
                         class: 'delete_sub_comment', id: "#{sub_comment.id}_delete", remote: true,
                         title: 'Delete comment', rel: 'tooltip' %> |
          <%= link_to 'edit' , edit_sub_comment_path(sub_comment.id)%>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/sub_comments/_sub_form.html.erb
<%= form_for @new_sub_comment, url: create_sub_comment_path, remote: true do |f|%>
    <div class="form-group">
      <%= f.hidden_field :comment_id , value: comment.id  %>
      <%= f.text_area :body, class: 'form-control' , rows: '3' %>
    </div>

    <%= f.submit 'Post your comment', class: 'btn btn-default sub_comment_submit' %>
<% end %>

app/views/sub_comments/destroy.js.erb
$('#sub_comment_<%= @sub_comment.id %>').remove();

app/views/sub_comments/edit.html.erb
<%= render 'edit_sub_comment'%>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <h2 id="log-in-title">Регистрация</h2>

    <%= form_for @user, html: { multipart: true } do |f| %>

        <%= render 'shared/error_messages' , object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :avatar %>
        <%= f.file_field :avatar %>


        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= image_tag @user.avatar.url  %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>